/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Project {
  'id' : bigint,
  'status' : ProjectStatus,
  'name' : string,
  'createdAt' : bigint,
  'submittedBy' : Principal,
  'description' : string,
  'category' : string,
  'price' : number,
}
export type ProjectStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'avatarUrl' : [] | [string],
  'githubLogin' : [] | [string],
  'provider' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveProject' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'exchangeGitHubCode' : ActorMethod<[string], string>,
  'getApprovedProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyProjects' : ActorMethod<[], Array<Project>>,
  'getPendingProjects' : ActorMethod<[], Array<Project>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectProject' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveGoogleProfile' : ActorMethod<[string, string, string], undefined>,
  'submitProject' : ActorMethod<[string, string, string, number, string], bigint>,
  'syncGitHubProfile' : ActorMethod<[string], UserProfile>,
  'unlockContact' : ActorMethod<[bigint], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
